/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kawayu_go_socket_android_TcpClient */

#ifndef _Included_com_kawayu_go_socket_android_TcpClient
#define _Included_com_kawayu_go_socket_android_TcpClient
#ifdef __cplusplus
extern "C" {
#endif
#undef com_kawayu_go_socket_android_TcpClient_DIS_NONE
#define com_kawayu_go_socket_android_TcpClient_DIS_NONE 0L
#undef com_kawayu_go_socket_android_TcpClient_DIS_RESET
#define com_kawayu_go_socket_android_TcpClient_DIS_RESET 1L
#undef com_kawayu_go_socket_android_TcpClient_DIS_NET_CHANGE
#define com_kawayu_go_socket_android_TcpClient_DIS_NET_CHANGE 2L
#undef com_kawayu_go_socket_android_TcpClient_DIS_NET_LOST
#define com_kawayu_go_socket_android_TcpClient_DIS_NET_LOST 3L
#undef com_kawayu_go_socket_android_TcpClient_DIS_KICKOUT
#define com_kawayu_go_socket_android_TcpClient_DIS_KICKOUT 4L
#undef com_kawayu_go_socket_android_TcpClient_DIS_LOGOUT
#define com_kawayu_go_socket_android_TcpClient_DIS_LOGOUT 5L
#undef com_kawayu_go_socket_android_TcpClient_DIS_CONNECT_TIMEOUT
#define com_kawayu_go_socket_android_TcpClient_DIS_CONNECT_TIMEOUT 6L
#undef com_kawayu_go_socket_android_TcpClient_DIS_SEND_REQ_TIMEOUT
#define com_kawayu_go_socket_android_TcpClient_DIS_SEND_REQ_TIMEOUT 7L
#undef com_kawayu_go_socket_android_TcpClient_DIS_PING_TIMEOUT
#define com_kawayu_go_socket_android_TcpClient_DIS_PING_TIMEOUT 8L
#undef com_kawayu_go_socket_android_TcpClient_NET_TYPE_UNKNOWN
#define com_kawayu_go_socket_android_TcpClient_NET_TYPE_UNKNOWN 0L
#undef com_kawayu_go_socket_android_TcpClient_NET_TYPE_WIFI
#define com_kawayu_go_socket_android_TcpClient_NET_TYPE_WIFI 1L
#undef com_kawayu_go_socket_android_TcpClient_NET_TYPE_MOBILE
#define com_kawayu_go_socket_android_TcpClient_NET_TYPE_MOBILE 2L
#undef com_kawayu_go_socket_android_TcpClient_NET_TYPE_NO_NET
#define com_kawayu_go_socket_android_TcpClient_NET_TYPE_NO_NET 3L
#undef com_kawayu_go_socket_android_TcpClient_CONN_IDLE
#define com_kawayu_go_socket_android_TcpClient_CONN_IDLE 0L
#undef com_kawayu_go_socket_android_TcpClient_CONN_CONNECTING
#define com_kawayu_go_socket_android_TcpClient_CONN_CONNECTING 1L
#undef com_kawayu_go_socket_android_TcpClient_CONN_CONNECTED
#define com_kawayu_go_socket_android_TcpClient_CONN_CONNECTED 2L
#undef com_kawayu_go_socket_android_TcpClient_CONN_DISCONNECTED
#define com_kawayu_go_socket_android_TcpClient_CONN_DISCONNECTED 3L
#undef com_kawayu_go_socket_android_TcpClient_CONN_FAILED
#define com_kawayu_go_socket_android_TcpClient_CONN_FAILED 4L
#undef com_kawayu_go_socket_android_TcpClient_CONN_KICKOUT
#define com_kawayu_go_socket_android_TcpClient_CONN_KICKOUT 5L
#undef com_kawayu_go_socket_android_TcpClient_ERR_CODE_NONE
#define com_kawayu_go_socket_android_TcpClient_ERR_CODE_NONE 0L
#undef com_kawayu_go_socket_android_TcpClient_ERR_CODE_NOT_CONNECTED
#define com_kawayu_go_socket_android_TcpClient_ERR_CODE_NOT_CONNECTED 1L
#undef com_kawayu_go_socket_android_TcpClient_ERR_CODE_TIMEOUT
#define com_kawayu_go_socket_android_TcpClient_ERR_CODE_TIMEOUT 2L
#undef com_kawayu_go_socket_android_TcpClient_ERR_CODE_LOSE_CONNECT
#define com_kawayu_go_socket_android_TcpClient_ERR_CODE_LOSE_CONNECT 3L
#undef com_kawayu_go_socket_android_TcpClient_SVR_DIS_CODE_NONE
#define com_kawayu_go_socket_android_TcpClient_SVR_DIS_CODE_NONE 0L
#undef com_kawayu_go_socket_android_TcpClient_SVR_DIS_CODE_KICKOFF
#define com_kawayu_go_socket_android_TcpClient_SVR_DIS_CODE_KICKOFF 1L
/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    initHostAndPort
 * Signature: (Ljava/lang/String;Ljava/lang/String;IZLcom/kawayu/go_socket_android/TcpClient/GetConnectInfoListener;)V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_initHostAndPort
  (JNIEnv *, jclass, jstring, jstring, jint, jboolean, jobject);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    makeSureConnected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_makeSureConnected
  (JNIEnv *, jclass);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    disconnectAsync
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_disconnectAsync
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    send
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BLcom/kawayu/go_socket_android/TcpClient/SendRespListener;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_send
  (JNIEnv *, jclass, jstring, jstring, jbyteArray, jobject);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    sendNoReply
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_sendNoReply
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    setOnConnStatusChange
 * Signature: (Lcom/kawayu/go_socket_android/TcpClient/ConnStatusChangeListener;)V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_setOnConnStatusChange
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    setOnSendReq
 * Signature: (Lcom/kawayu/go_socket_android/TcpClient/SendReqListener;)V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_setOnSendReq
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    setOnServerDisconnect
 * Signature: (Lcom/kawayu/go_socket_android/TcpClient/ServerDisconnectListener;)V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_setOnServerDisconnect
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    setHttpDnsListener
 * Signature: (Lcom/kawayu/go_socket_android/TcpClient/GetHttpDnsListener;)V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_setHttpDnsListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    setNetType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_setNetType
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_kawayu_go_socket_android_TcpClient
 * Method:    getConnectStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kawayu_go_1socket_1android_TcpClient_getConnectStatus
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
