/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kawayu_go_socket_android_TcpClient_GetHttpDnsListener */

#ifndef _Included_com_kawayu_go_socket_android_TcpClient_GetHttpDnsListener
#define _Included_com_kawayu_go_socket_android_TcpClient_GetHttpDnsListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
