/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kawayu_go_socket_android_TcpClient_ConnStatusChangeListener */

#ifndef _Included_com_kawayu_go_socket_android_TcpClient_ConnStatusChangeListener
#define _Included_com_kawayu_go_socket_android_TcpClient_ConnStatusChangeListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
