/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kawayu_go_socket_android_TcpClient_GetConnectInfoListener */

#ifndef _Included_com_kawayu_go_socket_android_TcpClient_GetConnectInfoListener
#define _Included_com_kawayu_go_socket_android_TcpClient_GetConnectInfoListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
